# Generated by Django 6.0.5 on 2026-05-25 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=50)),
                ('activity_value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('normalized_value', models.FloatField()),
                ('normalized_unit', models.CharField(max_length=50)),
                ('record_date', models.DateField()),
                ('is_suspicious', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.datasource')),
            ],
        ),
    ]
