# Generated by Django 6.0.5 on 2026-05-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='analyst_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='risk_score',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='LOW', max_length=20),
        ),
    ]
