# Generated by Django 6.0.5 on 2026-05-29 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('emissions', '0002_emissionrecord_analyst_note_and_more'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emissionrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='ingestion.datasource'),
        ),
    ]
