# Generated by Django 6.0.5 on 2026-05-28 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('emissions', '0002_emissionrecord_analyst_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='changed_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='record',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='emission_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.emissionrecord'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('UPDATED', 'UPDATED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
